#!/bin/bash

while true;do
echo -ne "AT\r\n" | microcom -X -t 10 /dev/ttyUSB3 >> /dev/null 2>&1
if [  $? -eq 0 ]
then
   break
else
   sleep 1
fi

done


imsi()
{
local Bval=$(echo -ne "AT+CIMI\r\n" | microcom -X -t 100 /dev/ttyUSB3)

if [[ $(("$Bval") 2>&1 | grep "ERROR\|microcom\|DELAYED\|BUSY\|NO CARRIER" ) ]]; then

echo ""

else 

echo "$Bval"| awk /^[0-9]/ | tr -d "\r"

fi
}

iccid()    
{     
local Bval=$(echo -ne "AT+CICCID\r\n" | microcom -X -t 100 /dev/ttyUSB3)
                                                                      
if [[ $(("$Bval") 2>&1 | grep "ERROR\|microcom\|DELAYED\|BUSY\|NO CARRIER" ) ]]; then                
                                                                      
echo ""                                                               
                                                                      
else                                                                  
                                                                      
echo "$Bval"| grep "+ICCID:" | tr -d "+ICCID: "                               
                                                      
fi                                                    
}

provider()                                                                              
{                                                                                    
local Bval=$(echo -ne "AT+CSPN?\r\n" | microcom -X -t 100 /dev/ttyUSB3)
                                                                                                            
if [[ $(("$Bval") 2>&1 | grep "ERROR\|microcom\|DELAYED\|BUSY\|NO CARRIER" ) ]]; then                       
                                                                                                            
echo ""                                                                                                     
                                                                                                            
else                                                                                                        
                                                                                                            
echo "$Bval"| grep "+CSPN: "  | tr -d ":" | sed 's/\<CSPN\>//g'

                                                                                                            
fi                                                                                                          
}

simstat()                                                                                                  
{                                                                                                           
local Bval=$(echo -ne "AT+CPIN?\r\n" | microcom -X -t 100 /dev/ttyUSB3)                                     
                                                                                                            
if [[ $(("$Bval") 2>&1 | grep "ERROR\|microcom\|DELAYED\|BUSY\|NO CARRIER" ) ]]; then                       
                                                                                                            
echo ""                                                                                                     
                                                                                                            
else                                                                                                        
                                                                                                            
echo "$Bval"| grep "+CPIN: "  | tr -d "1\",+:" | sed 's/\<CPIN\>//g'                                                                                                
                                                                                                            
fi                                                                                                          
}  

signalquality()                                                                                                   
{                                                                                                           
local Bval=$(echo -ne "AT+CSQ\r\n" | microcom -X -t 100 /dev/ttyUSB3)                                     
                                                                                                            
if [[ $(("$Bval") 2>&1 | grep "ERROR\|microcom\|DELAYED\|BUSY\|NO CARRIER" ) ]]; then                       
                                                                                                            
echo ""                                                                                                     
                                                                                                            
else                                                                                                        
                                                                                                            
echo "$Bval" | grep "+CSQ: "  | tr -d "+:" | sed 's/\<CSQ\>//g' | sed 's/\<99\>//g' | tr -d ", "                                                                                                
                                                                                                            
fi                                                                                                          
}


case "$1" in
        "--IMSI")
                imsi
                ;;
        "--ICCID")
              
                  iccid
                ;;

        "--Provider")
                provider
                 ;;
        "--SIMstat")
                simstat ;;
        "--SignalQuality")
                signalquality ;;
        "--Reset")
                echo -ne "AT+CRESET\r\n" | microcom -X -t 100 /dev/ttyUSB3 ;;
        "--RoamingActive")
                echo -ne "AT+CREG=2\r\n" | microcom -X -t 100 /dev/ttyUSB3 ;;
        "--RoamingDActive")
                echo -ne "AT+CREG=0\r\n" | microcom -X -t 100 /dev/ttyUSB3 ;;
        "--Irancell")
                echo -ne "AT+COPS=1,2,"43235"\r\n" | microcom -X -t 1000 /dev/ttyUSB3 ;;
        "--MCI")
                echo -ne "AT+COPS=1,2,"43211"\r\n" | microcom -X -t 1000 /dev/ttyUSB3 ;;
        "--Mobin")
                echo -ne "AT+COPS=1,2,"43244"\r\n" | microcom -X -t 1000 /dev/ttyUSB3 ;;
        "--LTE")
                echo -ne "AT+CNMP=38\r\n" | microcom -X -t 100 /dev/ttyUSB3 ;;
        "--WCDMA")           
                echo -ne "AT+CNMP=14\r\n" | microcom -X -t 100 /dev/ttyUSB3 ;;
        "--Auto")           
                echo -ne "AT+CNMP=2\r\n" | microcom -X -t 100 /dev/ttyUSB3 ;;
        "--Netstat")                                                             
                echo -ne "AT+CPSI?\r\n" | microcom -X -t 100 /dev/ttyUSB3 ;; 





        *)
                echo "Unknow parameter Please Use of the valid parameters
                --IMSI 
                --Provider
                --SIMstat 
                --SignalQuality
                --Reset
                --RoamingActive
                --RoamingDActive
                --Irancell
                --MCI
                --Mobin
                --LTE
                --WCDMA
                --Auto
                --Netstat               
                --ICCID
                
               " ;;



esac
