#!/bin/sh

rm -rf /tmp/providername
rm -rf /tmp/signal1 
rm -rf /tmp/signal2
while true;do
echo -ne "AT+CSPN?\r\n" | microcom -X -t 10 /dev/ttyUSB3 > /tmp/providername
echo -ne "AT+CSQ\r\n" | microcom -X -t 10 /dev/ttyUSB3 > /tmp/signal1
echo -ne "AT+CPSI?\r\n" | microcom -X -t 500 /dev/ttyUSB3 > /tmp/signal2



sleep 5
done
